### PR TITLE
updated bg for brands

### PR DESCRIPTION
**Pull request by beingabstrac**

### CODE REVIEW

**Comment by beingabstrac** [comment]
now?

**Comment by m-nikhil** [comment]
Now its matching the product page....They asked for white background

**Comment by beingabstrac** [comment]
slider images?

**Comment by m-nikhil** [comment]
good da.. developement/resources.../layout2 has the images

**Comment by beingabstrac** [comment]
footer?

**Comment by m-nikhil** [comment]
they didnt give yey

**Pull request merged**
